import {
  BadgeCheck,
  Banknote,
  BriefcaseBusiness,
  CircleUserRound,
  FileCheck2,
  Fingerprint,
  Landmark,
  ScanFace,
} from "lucide-react";
import type { SelectOption } from "../../components/ui/CustomSelect";
import type { ApplicationOption, StepDefinition } from "./types";

export const allSteps: StepDefinition[] = [
  {
    id: "personal",
    shortLabel: "Personal",
    label: "Personal",
    description: "Applicant and investment details",
    icon: CircleUserRound,
  },
  {
    id: "business",
    shortLabel: "Business",
    label: "Business",
    description: "Assessment, tax and activity",
    icon: BriefcaseBusiness,
  },
  {
    id: "identity",
    shortLabel: "Selfie",
    label: "Prove It’s You",
    description: "Live identity selfie",
    icon: ScanFace,
  },
  {
    id: "bank",
    shortLabel: "Bank",
    label: "External Bank Account",
    description: "Settlement account verification",
    icon: Landmark,
  },
  {
    id: "cash",
    shortLabel: "Cash",
    label: "Cash Accounts",
    description: "Select account currencies",
    icon: Banknote,
  },
  {
    id: "documents",
    shortLabel: "Proof",
    label: "Upload Proof",
    description: "Identity and address evidence",
    icon: FileCheck2,
  },
  {
    id: "signature",
    shortLabel: "E-Signature",
    label: "E-Signature",
    description: "Authorised signatory details",
    icon: Fingerprint,
  },
  {
    id: "review",
    shortLabel: "Review",
    label: "Review and Submit",
    description: "Confirm and securely submit",
    icon: BadgeCheck,
  },
];

export const APPLICATION_OPTIONS: ApplicationOption[] = [
  {
    value: "individual",
    label: "Individual",
    description: "An account held by one individual applicant",
    headerTitle: "Individual application",
  },
  {
    value: "joint-same",
    label: "Husband-and-wife joint account — same address",
    description: "Joint applicants who share a residential address",
    headerTitle: "Joint Account application",
  },
  {
    value: "joint-different-name",
    label: "Different-surname joint account — same address",
    description: "Joint applicants with different surnames at one address",
    headerTitle: "Joint Account application",
  },
  {
    value: "joint-different-address",
    label: "Joint account — different addresses",
    description: "Joint applicants who have separate residential addresses",
    headerTitle: "Joint Account application",
  },
  {
    value: "sole-trader",
    label: "Sole Trader",
    description: "An individual applying in their capacity as a sole trader",
    headerTitle: "Sole trader application",
  },
];

export const ASSESSMENT_OPTIONS: SelectOption[] = [
  {
    value: "australian",
    label: "Australian",
    description: "Australian customer assessment",
  },
  {
    value: "foreign",
    label: "Foreign",
    description: "International customer assessment",
  },
];

export const INVESTMENT_CURRENCY_OPTIONS: SelectOption[] = [
  { value: "AUD", label: "Australian dollar (AUD)" },
  { value: "USD", label: "US dollar (USD)" },
  { value: "GBP", label: "British pound (GBP)" },
  { value: "EUR", label: "Euro (EUR)" },
  { value: "SGD", label: "Singapore dollar (SGD)" },
  { value: "HKD", label: "Hong Kong dollar (HKD)" },
];

export const BANK_CURRENCY_OPTIONS: SelectOption[] = [
  ...INVESTMENT_CURRENCY_OPTIONS,
  { value: "NZD", label: "New Zealand dollar (NZD)" },
  { value: "JPY", label: "Japanese yen (JPY)" },
  { value: "CAD", label: "Canadian dollar (CAD)" },
  { value: "CHF", label: "Swiss franc (CHF)" },
];

export const PHOTO_ID_OPTIONS: SelectOption[] = [
  {
    value: "passport",
    label: "Passport",
    description: "Passport identity page",
  },
  {
    value: "driving-licence",
    label: "Driving licence",
    description: "Front and back of a current licence",
  },
  {
    value: "photo-id",
    label: "Photo ID",
    description: "Other current government-issued photo identification",
  },
];

export const ADDRESS_DOCUMENT_OPTIONS: SelectOption[] = [
  {
    value: "utility-bill",
    label: "Utility bill",
    description: "Recent electricity, gas, water or internet bill",
  },
  {
    value: "lease-agreement",
    label: "Lease agreement",
    description: "Current residential tenancy or lease agreement",
  },
  {
    value: "tax-document",
    label: "Tax document",
    description: "Recent government-issued tax assessment or notice",
  },
];

export const INVESTMENT_AMOUNT_OPTIONS: SelectOption[] = [
  { value: "$500k–$50 million", label: "$500,000 – $50 million" },
  { value: "$50–$100 million", label: "$50 million – $100 million" },
  { value: "$100 million+", label: "$100 million+" },
];

export const COUNTRY_OPTIONS: SelectOption[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Republic of the Congo",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "São Tomé and Príncipe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Türkiye",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Other",
].map((country) => ({ value: country, label: country }));

export const BUSINESS_NATURE_OPTIONS: SelectOption[] = [
  { value: "Accredited Investor", label: "Accredited Investor" },
  { value: "High Net-worth Individual", label: "High Net-worth Individual" },
  { value: "Sophisticated Investor", label: "Sophisticated Investor" },
  { value: "Wholesale Investor", label: "Wholesale Investor" },
];

export const BUSINESS_ACTIVITY_OPTIONS: SelectOption[] = [
  { value: "Capital Markets", label: "Capital Markets" },
  { value: "Commodities", label: "Commodities" },
  { value: "Financial Markets", label: "Financial Markets" },
  { value: "Other", label: "Other" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Stock Market", label: "Stock Market" },
];
